.\"
.\" Copyright (c) 2016 Sebastien Marie <semarie@online.fr>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt CHECKRESTART 8
.Os
.Sh NAME
.Nm checkrestart
.Nd help to find processes that need restarting after upgrade
.Sh SYNOPSIS
.Nm
.Op Fl v
.Op Fl M Ar core
.Op Fl N Ar system
.Op Fl W Ar swap
.Sh DESCRIPTION
.Nm
is a program designed to help to find processes that need restarting after
upgrade.
.Pp
.Nm
walks through the entire file table of the system, searching for processes
with a
.Dv VTEXT
node detached from the filesystem.
.Pp
By default,
.Nm
will output the pid and executable name of these running processes.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl v
Verbose mode.
.Nm
will additionally output the inode and mount point of the unlinked node.
.It Fl M Ar core
Extract values associated with the name list from the specified
core instead of the running kernel.
.It Fl N Ar system
Extract the name list from the specified system instead of the
running kernel.
.It Fl W Ar swap
When not using the running kernel, extract swap information from
the specified file.
.El
.Pp
The typical use case is:
.Bl -bullet
.It
start a long lived program.
.It
later, upgrade your packages via pkg_add -u.
.It
if the program is updated on disk, the running program is still
the previous one (without security fixes for example).
.It
.Nm
will tell you which processes belong to this category.
.El
.Sh SEE ALSO
.Xr fstat 1
.Sh HISTORY
The name
.Nm checkrestart
comes from a similar tool from
Debian
that relies on
.Xr lsof 1
for achieving the same purpose.
.Sh AUTHORS
.An -nosplit
.Nm
was written by
.An Sebastien Marie Aq Mt semarie@online.fr .
.Sh CAVEATS
Only
.Dv VTEXT
nodes are reported by
.Nm .
Some programs using old libraries aren't reported
due to lack of kernel support.
